### ISSUE TITLE
npm test fail

### ISSUE THREAD

**Issue by disjukr** [disjukr/yaksok.js#62]
왜 잘 되던게 갑자기 깨지지...
```
-- dump compiler results --
running "src/test/dump-js-exports.js"...TypeError: Function.prototype.toString is not generic
    at Function.toString (native)
    at Function.toString (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/core-js/modules/_redefine.js:31:1)
    at TextDumper._callee5$ (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/src/test/util.js:66:27)
    at tryCatch (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/regenerator/runtime.js:88:15)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/regenerator/runtime.js:341:1)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/regenerator/runtime.js:121:1)
    at step (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:35:1
    at new Promise (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/core-js/library/modules/es6.promise.js:193:1)
    at TextDumper.<anonymous> (/Users/disjukr/Dropbox/project/yaksok.js/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:14:1)
```

**Comment by disjukr** [comment]
?????? 트래비스에서 새로 돌렸는데 통과하네 뭐지 뭐엉어어어어어지ㅣ이이ㅣ이이ㅣ
